/**
 * Pellicule Nuxt Module
 *
 * Adds deterministic video rendering support to Nuxt apps.
 *
 * Usage in nuxt.config.ts:
 *   export default defineNuxtConfig({
 *     modules: ['pellicule/nuxt']
 *   })
 *
 * What this module does:
 *   1. Adds a hidden /pellicule page that Playwright navigates to for rendering
 *   2. Registers the defineVideoConfig() macro Vite plugin
 *   3. Generates a virtual module that glob-imports video components
 */

import { defineNuxtModule, addTemplate, extendPages } from '@nuxt/kit'
import { resolve } from 'path'
import { fileURLToPath } from 'url'
import { pelliculeMacroVitePlugin } from '../macros/define-video-config.js'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

export default defineNuxtModule({
  meta: {
    name: 'pellicule',
    configKey: 'pellicule',
    compatibility: {
      nuxt: '>=3.0.0'
    }
  },

  defaults: {
    // In Nuxt 4, srcDir defaults to app/ so ~ = <project>/app/
    // ~/videos resolves to <project>/app/videos/ which is the convention
    videosDir: '~/videos'
  },

  setup(options, nuxt) {
    // ── 1. Generate virtual module with video component glob ─────────
    //
    // Creates a .nuxt/pellicule/video-components.mjs file that uses
    // import.meta.glob to discover all .vue files in the videos directory.
    // Eager mode so components are available synchronously when the
    // render page resolves them.

    const videosGlob = options.videosDir.replace(/\/$/, '') + '/**/*.vue'

    const template = addTemplate({
      filename: 'pellicule/video-components.mjs',
      getContents() {
        return [
          '// Auto-generated by pellicule/nuxt module',
          `const videoModules = import.meta.glob('${videosGlob}', { eager: true })`,
          '',
          '/**',
          ' * Resolve a video component by name.',
          ' * @param {string} name - Component name (e.g., "Demo" or "Demo.vue")',
          ' * @returns {object|null} The Vue component, or null if not found',
          ' */',
          'export function resolveVideoComponent(name) {',
          '  const target = name.endsWith(\'.vue\') ? name : name + \'.vue\'',
          '',
          '  for (const [path, mod] of Object.entries(videoModules)) {',
          '    const filename = path.split(\'/\').pop()',
          '    if (filename === target) return mod.default || mod',
          '  }',
          '',
          '  return null',
          '}',
          '',
          'export function getAvailableVideos() {',
          '  return Object.keys(videoModules).map(path =>',
          '    path.split(\'/\').pop().replace(/\\.vue$/, \'\')',
          '  )',
          '}'
        ].join('\n')
      }
    })

    // ── 2. Add the /pellicule render page ───────────────────────────

    extendPages((pages) => {
      pages.push({
        name: 'pellicule-render',
        path: '/pellicule',
        file: resolve(__dirname, 'runtime/render-page.vue')
      })
    })

    // Disable SSR for the render page (needs client-side window globals)
    nuxt.options.routeRules = nuxt.options.routeRules || {}
    nuxt.options.routeRules['/pellicule'] = { ssr: false }

    // Alias so the render page can import the generated virtual module
    nuxt.options.alias['#pellicule/video-components'] = template.dst

    // ── 3. Register the defineVideoConfig macro Vite plugin ──────────
    //
    // This strips defineVideoConfig() calls at compile time, same as
    // the Vite and Rsbuild adapters do for their bundler modes.

    nuxt.hook('vite:extendConfig', (viteConfig) => {
      viteConfig.plugins = viteConfig.plugins || []
      viteConfig.plugins.push(pelliculeMacroVitePlugin())
    })
  }
})
